name: cpu_instrs

on:
  pull_request:
    paths-ignore:
      - "assets/**"
  push:
    paths-ignore:
      - "assets/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run CPU Instructions Test
        run: bash ci/test-cpu-instrs.sh
